# Generated by Django 4.0.3 on 2022-05-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodation',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='regions',
            old_name='discription',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='listofcountries',
            name='discription',
        ),
        migrations.AddField(
            model_name='listofcountries',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='availability',
            field=models.PositiveIntegerField(verbose_name='количество свободных номеров'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='room_desc',
            field=models.TextField(blank=True, max_length=60, verbose_name='краткое описание комнаты'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='short_desc',
            field=models.TextField(blank=True, max_length=60, verbose_name='краткое описание продукта'),
        ),
    ]
